### PR TITLE
Add in-place versions of kron and batched_kron

### LINKED ISSUE #53: Implement in-place kron and batched_kron
Wouldn't it be enough define 

```julia
function kron!(C::CuArray{T3}, A::Union{CuArray{T1}, Adjoint{<:Any, <:CuArray{T1}}}, B::Union{CuArray{T2}, Adjoint{<:Any, <:CuArray{T2}}}) where {T1, T2, T3} 
```
by reusing the out-of-place version

https://github.com/QuantumBFS/CuYao.jl/blob/ba08a02477fe8115959c5759f8ceb5767f48248e/src/CUDApatch.jl#L76-L91

but replace `res` with `C` and adding some bounds checks etc.?

Would the samee apply to `batched_kron!`?

### PR DESCRIPTION
**Pull request by elisno**
Resolves #53 

I started by reusing `kron` and `batched_kron` from this package.

- [x] Check bounds

- [x] Add docstrings

- [x] Add tests

- [ ] (Optional) Benchmarks?

@Roger-luo @GiggleLiu 
What more needs to be done?

### CODE REVIEW

**Comment by GiggleLiu** [comment]
Good, this list if fine.

**Comment by Roger-luo** [comment]
Hi @elisno is this ready for review? It looks good to me.

**Comment by Roger-luo** [comment]
Very neat work! Thanks @elisno ! I'll merge this first and we could consider move some common thing to a single package for Kronecker.jl in the future.

**Comment by elisno** [comment]
Sorry for the delay. I've been using GPUs on a cluster to try this out, but the queues recently got longer.

**Pull request merged**
