### PR TITLE
update CUDA

### PR DESCRIPTION
**Pull request by GiggleLiu**

### CODE REVIEW

**Comment by GiggleLiu** [comment]
@Roger-luo Since I only tested this PR locally, can you run the tests on your local host to make sure it works and get it merged.

**Comment by Roger-luo** [comment]
what happened to our CI?

**Comment by GiggleLiu** [comment]
I have no clue

**Comment by Roger-luo** [comment]
@GiggleLiu  We need to drop 1.6- support here, the new method overlay hack in CUDA only works on 1.6+

I think we also need a minor version bump for this update too.

**Comment by Roger-luo** [comment]
OK LGTM

**Pull request merged**
